### ISSUE TITLE
2.0 Release Checklist

### ISSUE THREAD

**Issue by medeor413** [medeor413/Red_Star#160]
- [x] Complete all [2.0 milestone](https://github.com/medeor413/Red_Star/milestone/2) issues (excepting this one of course)
- [x] Ensure wiki documentation is up to date, including Commands, RSLisp, Configuration, Plugins...
- [x] Ensure config.json.default is up to date
- [x] Update README with new information
- [x] Document Red Star extra plugins repo more
- [x] Run one more code inspection and give everything a thorough look-over
- [x] Bump version number in rs_version to 2.0.0-release
- [x] Release 2.0!
- [x] Put it up on the main PyPI
